import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, variables?: Record<string, string | number>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.callLogs': 'Call Logs',
    'nav.subAccounts': 'Sub-Accounts',
    'nav.users': 'Users',
    'nav.settings': 'Settings',
    'header.selectDate': 'Select date range',
    'header.clearDate': 'Clear date range',
    'auth.email': 'Email address',
    'auth.password': 'Password',
    'auth.signin': 'Sign in',
    'app.loading': 'Loading...',
    'app.error': 'Error',
    'sidebar.title': 'Voice.AI',
    'sidebar.subAccount': 'Sub-Account',
    'sidebar.selectLocation': 'Select Location',
    'sidebar.noSubAccounts': 'No sub-accounts',
    'sidebar.mainMenu': 'Main Menu',
    'app.accessError': 'Access Error',
    'app.configureToken': 'Configure API Token',
    'app.loadingCallLogs': 'Loading call logs...',
    'app.allAgents': 'All Agents',
    'app.unknownAgent': 'Unknown Agent',
    'app.totalRecords': 'Total {count} records found',
    'metrics.attempted': 'Attempted Calls',
    'metrics.connected': 'Connected Calls',
    'metrics.actions': 'Actions Triggered',
    'modal.configureToken': 'Configure Token',
    'modal.enterToken': 'Enter the Private Integration Token (PIT) for {name}.',
    'modal.pasteToken': 'Paste PIT token here...',
    'modal.requiredScopes': 'Required Scopes (Click to copy):',
    'modal.viewAgents': 'View Agents in Agent Studio',
    'modal.viewGoals': 'View Voice AI Agent Goals',
    'modal.viewVoiceAgents': 'View Voice AI Agents',
    'modal.viewDashboard': 'View Voice AI Dashboard',
    'modal.howToFind': 'How to find your token:',
    'modal.step1': 'Log in to your GoHighLevel dashboard.',
    'modal.step2': 'Switch to the specific Sub-Account.',
    'modal.step3': 'Navigate to Settings > Private Integrations > Create New Integration.',
    'modal.step4': 'Add the required scopes above.',
    'modal.step5': 'Copy the generated token and paste it above.',
    'modal.cancel': 'Cancel',
    'modal.saveToken': 'Save Token',
    'modal.saving': 'Saving...',
    'callsTable.search': 'Search by name...',
    'callsTable.agent': 'Agent',
    'callsTable.contact': 'Contact',
    'callsTable.date': 'Date',
    'callsTable.duration': 'Duration',
    'callsTable.status': 'Status',
    'callsTable.actions': 'Actions',
    'callsTable.noCalls': 'No calls found matching your criteria',
    'callsTable.showing': 'Showing 1 to {count} of {total} results',
    'callsTable.summary': 'Summary',
    'chart.callOutcomes': 'Call Outcomes',
    'chart.humanAnswered': 'Human Answered',
    'chart.voicemail': 'Voicemail',
    'chart.noAnswer': 'No Answer',
    'chart.failed': 'Failed',
    'summaryModal.callDetails': 'Call Details',
    'summaryModal.summaryTab': 'Summary',
    'summaryModal.transcriptTab': 'Transcript',
    'summaryModal.metadata': 'Metadata',
    'summaryModal.agentId': 'Agent ID',
    'summaryModal.contactId': 'Contact ID',
    'summaryModal.trialCall': 'Trial Call',
    'summaryModal.extractedData': 'Extracted Data',
    'summaryModal.yes': 'Yes',
    'summaryModal.no': 'No',
    'summaryModal.noSummary': 'No summary available.',
    'summaryModal.title': 'Call Summary',
    'summaryModal.close': 'Close',
    'summaryModal.contactInfo': 'Contact Info',
    'summaryModal.phone': 'Phone:',
    'summaryModal.status': 'Status:',
    'summaryModal.duration': 'Duration:',
    'summaryModal.date': 'Date:',
    'summaryModal.callSummary': 'Call Summary',
    'summaryModal.transcript': 'Transcript',
    'summaryModal.noTranscript': 'No transcript available.',
    'settings.title': 'Settings',
    'tutorial.subAccountSelect': 'Select the sub-account you want to view or manage data for.',
    'tutorial.callLogs': 'View detailed analytics and history for your calls.',
    'tutorial.subAccounts': 'Manage private integration tokens for your sub-accounts.',
    'tutorial.users': 'Manage access and create logins for your clients and team members.',
    'tutorial.settings': 'Update your profile, password, or application settings here.',
    'tutorial.datePicker': 'Filter your data by selecting a date range.',
    'tutorial.language': 'Switch between English and Spanish.',
    'tutorial.subAccountSelectTitle': 'Sub-Accounts',
    'tutorial.callLogsTitle': 'Call Analytics',
    'tutorial.subAccountsTitle': 'Manage Tokens',
    'tutorial.usersTitle': 'Team & Clients',
    'tutorial.settingsTitle': 'Account Settings',
    'tutorial.datePickerTitle': 'Time Filters',
    'tutorial.languageTitle': 'Language Preferences',
    'tutorial.agentSelectTitle': 'Agent Selection',
    'tutorial.agentSelect': 'Filter calls by a specific agent or view all agents at once.',
    'tutorial.searchFieldTitle': 'Search Calls',
    'tutorial.searchField': 'Quickly find specific calls by searching for contact names or numbers.',
    'tutorial.summaryButtonTitle': 'Call Summary',
    'tutorial.summaryButton': 'Click here to view detailed insights, transcriptions, and extracted data from a call.',
    'tutorial.addTokenTitle': 'Manage Tokens',
    'tutorial.addToken': 'Add or update the Private Integration Token to enable data fetching for this sub-account.',
    'tutorial.userEmailTitle': 'User Email',
    'tutorial.userEmail': 'Enter the email address for the new user.',
    'tutorial.userPasswordTitle': 'User Password',
    'tutorial.userPassword': 'Set a secure password for the new user.',
    'tutorial.userRoleTitle': 'User Role',
    'tutorial.userRole': 'Choose between Client (restricted access) and Admin (full access).',
    'tutorial.userLocationTitle': 'Assigned Location',
    'tutorial.userLocation': 'For clients, assign the specific sub-account they can view.',
    'tutorial.addUserBtnTitle': 'Add User',
    'tutorial.addUserBtn': 'Click to create the new user account.',
    'tutorial.settingsApiKeyTitle': 'Agency API Key',
    'tutorial.settingsApiKey': 'Update your GoHighLevel Agency API key here to keep sub-accounts synced.',
    'tutorial.settingsPasswordTitle': 'Change Password',
    'tutorial.settingsPassword': 'Update your account password for security.',
    'tutorial.start': 'Start Tutorial',
    'settings.help': 'Help & Support',
    'settings.helpDesc': 'Need help navigating the dashboard?',
    'settings.keySaved': 'Agency API Key saved successfully.',
    'settings.keyFailed': 'Failed to save Agency API Key.',
    'settings.keyError': 'Error saving key.',
    'settings.passwordSaved': 'Password updated successfully.',
    'settings.passwordFailed': 'Failed to change password.',
    'settings.agencySettings': 'Agency Settings',
    'settings.agencySettingsDesc': 'Configure your GoHighLevel Agency API settings securely.',
    'settings.newAgencyKey': 'New Agency API Key',
    'settings.newAgencyKeyPlaceholder': 'Enter new Agency API Key to update',
    'settings.agencyKeyHint': 'This key is used to fetch the list of sub-accounts from GoHighLevel. For security, the current key is not displayed.',
    'settings.saveSettings': 'Save Settings',
    'settings.saving': 'Saving...',
    'settings.security': 'Security',
    'settings.securityDesc': 'Update your account password.',
    'settings.oldPassword': 'Old Password',
    'settings.oldPasswordPlaceholder': 'Current password',
    'settings.newPassword': 'New Password',
    'settings.newPasswordPlaceholder': 'New password',
    'settings.updatePassword': 'Update Password',
    'settings.updating': 'Updating...',
    'settings.description': 'Manage your application preferences and configuration.',
    'settings.profile': 'User Profile',
    'settings.email': 'Email',
    'settings.role': 'Role',
    'settings.appConfig': 'Application Configuration',
    'settings.appConfigDesc': 'System settings and defaults',
    'settings.timezone': 'Timezone',
    'settings.language': 'Language',
    'subaccounts.title': 'Sub-Accounts',
    'subaccounts.noAccounts': 'No sub-accounts found. Check your Agency API key in Settings.',
    'subaccounts.loadingTokens': 'Loading tokens...',
    'subaccounts.description': 'Manage Private Integration Tokens for your sub-accounts.',
    'subaccounts.locationName': 'Location Name',
    'subaccounts.locationId': 'Location ID',
    'subaccounts.status': 'Status',
    'subaccounts.current': 'Current',
    'subaccounts.configured': 'Configured',
    'subaccounts.missingToken': 'Missing Token',
    'subaccounts.update': 'Update',
    'subaccounts.addToken': 'Add Token',
    'users.title': 'Users',
    'users.createdSuccess': 'User created successfully',
    'users.createFailed': 'Failed to create user',
    'users.deleteConfirm': 'Are you sure you want to delete {email}?',
    'users.delete': 'Delete',
    'users.description': 'Manage team members and client access to the dashboard.',
    'users.search': 'Search users...',
    'users.addUser': 'Add User',
    'users.user': 'User',
    'users.role': 'Role',
    'users.locations': 'Locations',
    'users.joined': 'Joined',
    'users.allLocations': 'All Locations',
    'users.assignedLocation': 'Assigned Location',
    'users.selectLocation': 'Select Location',
    'users.unassigned': 'Unassigned',
    'users.client': 'Client',
    'users.admin': 'Admin',
    'users.noUsers': 'No users found matching your criteria',
    'login.welcome': 'Welcome Back',
    'login.subtitle': 'Sign in to Dashboard',
    'login.portal': 'Voice.AI Client & Agency Portal',
    'login.emailAddress': 'Email address',
    'login.password': 'Password',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing in...',
    'login.demoAdmin': 'Demo Admin',
    'login.demoClient': 'Demo Client',
    'login.error': 'Invalid credentials. Try using the demo accounts.',
    'header.logout': 'Logout',
  },
  es: {
    'nav.callLogs': 'Registros de llamadas',
    'nav.subAccounts': 'Subcuentas',
    'nav.users': 'Usuarios',
    'nav.settings': 'Ajustes',
    'header.selectDate': 'Seleccionar fechas',
    'header.clearDate': 'Borrar fechas',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.signin': 'Iniciar sesión',
    'app.loading': 'Cargando...',
    'app.error': 'Error',
    'sidebar.title': 'Voice.AI',
    'sidebar.subAccount': 'Subcuenta',
    'sidebar.selectLocation': 'Seleccionar ubicación',
    'sidebar.noSubAccounts': 'Sin subcuentas',
    'sidebar.mainMenu': 'Menú Principal',
    'app.accessError': 'Error de Acceso',
    'app.configureToken': 'Configurar Token de API',
    'app.loadingCallLogs': 'Cargando registros de llamadas...',
    'app.allAgents': 'Todos los Agentes',
    'app.unknownAgent': 'Agente Desconocido',
    'app.totalRecords': 'Total de {count} registros encontrados',
    'metrics.attempted': 'Llamadas Intentadas',
    'metrics.connected': 'Llamadas Conectadas',
    'metrics.actions': 'Acciones Disparadas',
    'modal.configureToken': 'Configurar Token',
    'modal.enterToken': 'Ingresa el Token de Integración Privada (PIT) para {name}.',
    'modal.pasteToken': 'Pega el token PIT aquí...',
    'modal.requiredScopes': 'Alcances Requeridos (Haz clic para copiar):',
    'modal.viewAgents': 'Ver Agentes en Agent Studio',
    'modal.viewGoals': 'Ver Metas del Agente de Voz AI',
    'modal.viewVoiceAgents': 'Ver Agentes de Voz AI',
    'modal.viewDashboard': 'Ver Panel de Voz AI',
    'modal.howToFind': 'Cómo encontrar tu token:',
    'modal.step1': 'Inicia sesión en tu panel de GoHighLevel.',
    'modal.step2': 'Cambia a la Subcuenta específica.',
    'modal.step3': 'Navega a Configuración > Integraciones Privadas > Crear Nueva Integración.',
    'modal.step4': 'Agrega los alcances requeridos de arriba.',
    'modal.step5': 'Copia el token generado y pégalo arriba.',
    'modal.cancel': 'Cancelar',
    'modal.saveToken': 'Guardar Token',
    'modal.saving': 'Guardando...',
    'callsTable.search': 'Buscar por nombre...',
    'callsTable.agent': 'Agente',
    'callsTable.contact': 'Contacto',
    'callsTable.date': 'Fecha',
    'callsTable.duration': 'Duración',
    'callsTable.status': 'Estado',
    'callsTable.actions': 'Acciones',
    'callsTable.noCalls': 'No se encontraron llamadas que coincidan con sus criterios',
    'callsTable.showing': 'Mostrando 1 a {count} de {total} resultados',
    'callsTable.summary': 'Resumen',
    'chart.callOutcomes': 'Resultados de Llamadas',
    'chart.humanAnswered': 'Contestada por Humano',
    'chart.voicemail': 'Buzón de Voz',
    'chart.noAnswer': 'Sin Respuesta',
    'chart.failed': 'Fallida',
    'summaryModal.callDetails': 'Detalles de la Llamada',
    'summaryModal.summaryTab': 'Resumen',
    'summaryModal.transcriptTab': 'Transcripción',
    'summaryModal.metadata': 'Metadatos',
    'summaryModal.agentId': 'ID de Agente',
    'summaryModal.contactId': 'ID de Contacto',
    'summaryModal.trialCall': 'Llamada de Prueba',
    'summaryModal.extractedData': 'Datos Extraídos',
    'summaryModal.yes': 'Sí',
    'summaryModal.no': 'No',
    'summaryModal.noSummary': 'Sin resumen disponible.',
    'summaryModal.title': 'Resumen de Llamada',
    'summaryModal.close': 'Cerrar',
    'summaryModal.contactInfo': 'Información de Contacto',
    'summaryModal.phone': 'Teléfono:',
    'summaryModal.status': 'Estado:',
    'summaryModal.duration': 'Duración:',
    'summaryModal.date': 'Fecha:',
    'summaryModal.callSummary': 'Resumen de Llamada',
    'summaryModal.transcript': 'Transcripción',
    'summaryModal.noTranscript': 'No hay transcripción disponible.',
    'settings.title': 'Ajustes',
    'tutorial.subAccountSelect': 'Selecciona la subcuenta para la que deseas ver o gestionar datos.',
    'tutorial.callLogs': 'Visualiza analíticas detalladas y el historial de tus llamadas.',
    'tutorial.subAccounts': 'Gestiona tokens de integración privados para tus subcuentas.',
    'tutorial.users': 'Gestiona el acceso y crea inicios de sesión para tus clientes y miembros del equipo.',
    'tutorial.settings': 'Actualiza tu perfil, contraseña o ajustes de la aplicación aquí.',
    'tutorial.datePicker': 'Filtra tus datos seleccionando un rango de fechas.',
    'tutorial.language': 'Cambia entre Inglés y Español.',
    'tutorial.subAccountSelectTitle': 'Subcuentas',
    'tutorial.callLogsTitle': 'Analíticas de Llamadas',
    'tutorial.subAccountsTitle': 'Gestionar Tokens',
    'tutorial.usersTitle': 'Equipo y Clientes',
    'tutorial.settingsTitle': 'Ajustes de Cuenta',
    'tutorial.datePickerTitle': 'Filtros de Tiempo',
    'tutorial.languageTitle': 'Preferencias de Idioma',
    'tutorial.agentSelectTitle': 'Selección de Agente',
    'tutorial.agentSelect': 'Filtra las llamadas por un agente específico o ve todos los agentes a la vez.',
    'tutorial.searchFieldTitle': 'Buscar Llamadas',
    'tutorial.searchField': 'Encuentra rápidamente llamadas específicas buscando nombres o números.',
    'tutorial.summaryButtonTitle': 'Resumen de Llamada',
    'tutorial.summaryButton': 'Haz clic aquí para ver detalles, transcripciones y datos extraídos.',
    'tutorial.addTokenTitle': 'Gestionar Tokens',
    'tutorial.addToken': 'Agrega o actualiza el Token para habilitar la obtención de datos.',
    'tutorial.userEmailTitle': 'Correo del Usuario',
    'tutorial.userEmail': 'Ingresa el correo electrónico para el nuevo usuario.',
    'tutorial.userPasswordTitle': 'Contraseña',
    'tutorial.userPassword': 'Establece una contraseña segura para el nuevo usuario.',
    'tutorial.userRoleTitle': 'Rol del Usuario',
    'tutorial.userRole': 'Elige entre Cliente (acceso restringido) y Administrador (acceso total).',
    'tutorial.userLocationTitle': 'Ubicación Asignada',
    'tutorial.userLocation': 'Para clientes, asigna la subcuenta específica que pueden ver.',
    'tutorial.addUserBtnTitle': 'Añadir Usuario',
    'tutorial.addUserBtn': 'Haz clic para crear la cuenta de usuario.',
    'tutorial.settingsApiKeyTitle': 'Clave API de Agencia',
    'tutorial.settingsApiKey': 'Actualiza tu clave API de GoHighLevel aquí para sincronizar subcuentas.',
    'tutorial.settingsPasswordTitle': 'Cambiar Contraseña',
    'tutorial.settingsPassword': 'Actualiza tu contraseña para mayor seguridad.',
    'tutorial.start': 'Iniciar Tutorial',
    'settings.help': 'Ayuda y Soporte',
    'settings.helpDesc': '¿Necesitas ayuda para navegar por el panel?',
    'settings.keySaved': 'Clave API de Agencia guardada exitosamente.',
    'settings.keyFailed': 'Error al guardar la Clave API de Agencia.',
    'settings.keyError': 'Error al guardar la clave.',
    'settings.passwordSaved': 'Contraseña actualizada exitosamente.',
    'settings.passwordFailed': 'Error al cambiar la contraseña.',
    'settings.agencySettings': 'Ajustes de Agencia',
    'settings.agencySettingsDesc': 'Configura tus ajustes de la API de Agencia de GoHighLevel de forma segura.',
    'settings.newAgencyKey': 'Nueva Clave API de Agencia',
    'settings.newAgencyKeyPlaceholder': 'Ingresa nueva Clave API de Agencia para actualizar',
    'settings.agencyKeyHint': 'Esta clave se utiliza para obtener la lista de subcuentas desde GoHighLevel. Por seguridad, la clave actual no se muestra.',
    'settings.saveSettings': 'Guardar Ajustes',
    'settings.saving': 'Guardando...',
    'settings.security': 'Seguridad',
    'settings.securityDesc': 'Actualiza la contraseña de tu cuenta.',
    'settings.oldPassword': 'Contraseña Antigua',
    'settings.oldPasswordPlaceholder': 'Contraseña actual',
    'settings.newPassword': 'Nueva Contraseña',
    'settings.newPasswordPlaceholder': 'Nueva contraseña',
    'settings.updatePassword': 'Actualizar Contraseña',
    'settings.updating': 'Actualizando...',
    'settings.description': 'Administra las preferencias y configuración de tu aplicación.',
    'settings.profile': 'Perfil de Usuario',
    'settings.email': 'Correo electrónico',
    'settings.role': 'Rol',
    'settings.appConfig': 'Configuración de la Aplicación',
    'settings.appConfigDesc': 'Ajustes del sistema y valores predeterminados',
    'settings.timezone': 'Zona Horaria',
    'settings.language': 'Idioma',
    'subaccounts.title': 'Subcuentas',
    'subaccounts.noAccounts': 'No se encontraron subcuentas. Revisa tu Clave API de Agencia en Ajustes.',
    'subaccounts.loadingTokens': 'Cargando tokens...',
    'subaccounts.description': 'Administra Tokens de Integración Privada para tus subcuentas.',
    'subaccounts.locationName': 'Nombre de Ubicación',
    'subaccounts.locationId': 'ID de Ubicación',
    'subaccounts.status': 'Estado',
    'subaccounts.current': 'Actual',
    'subaccounts.configured': 'Configurado',
    'subaccounts.missingToken': 'Token Faltante',
    'subaccounts.update': 'Actualizar',
    'subaccounts.addToken': 'Añadir Token',
    'users.title': 'Usuarios',
    'users.createdSuccess': 'Usuario creado exitosamente',
    'users.createFailed': 'Error al crear usuario',
    'users.deleteConfirm': '¿Estás seguro de que deseas eliminar a {email}?',
    'users.delete': 'Eliminar',
    'users.description': 'Administra miembros del equipo y acceso de clientes al panel.',
    'users.search': 'Buscar usuarios...',
    'users.addUser': 'Añadir Usuario',
    'users.user': 'Usuario',
    'users.role': 'Rol',
    'users.locations': 'Ubicaciones',
    'users.joined': 'Unido',
    'users.allLocations': 'Todas las Ubicaciones',
    'users.assignedLocation': 'Ubicación Asignada',
    'users.selectLocation': 'Seleccionar Ubicación',
    'users.unassigned': 'Sin Asignar',
    'users.client': 'Cliente',
    'users.admin': 'Admin',
    'users.noUsers': 'No se encontraron usuarios',
    'login.welcome': 'Bienvenido de nuevo',
    'login.subtitle': 'Iniciar sesión en el Panel',
    'login.portal': 'Voice.AI Portal para Clientes y Agencias',
    'login.emailAddress': 'Correo electrónico',
    'login.password': 'Contraseña',
    'login.signIn': 'Iniciar Sesión',
    'login.signingIn': 'Iniciando sesión...',
    'login.demoAdmin': 'Admin Demo',
    'login.demoClient': 'Cliente Demo',
    'login.error': 'Credenciales inválidas. Intente usar las cuentas demo.',
    'header.logout': 'Cerrar sesión',
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key
});

export const LanguageProvider: React.FC<{children: React.ReactNode}> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('ghl_lang') as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('ghl_lang', language);
  }, [language]);

  const t = (key: string, variables?: Record<string, string | number>) => {
    let result = translations[language]?.[key] || key;
    if (variables) {
      Object.keys(variables).forEach(varKey => {
        result = result.replace(`{${varKey}}`, String(variables[varKey]));
      });
    }
    return result;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
